title: Rons Jekyll Testing
email: ron@fromex.net
description: Just doing some testing on stuff
baseurl: "/jekyll-minima-testing" # the subpath of your site, e.g. /blog
url: https://rdyar.github.io # the base hostname & protocol for your site, e.g. http://example.com
#linkedin_username: 
github_username: rdyar

# Build settings
theme: minima
plugins:
  - jekyll-feed
